content = open('atlas/vision/capture.py', 'r', encoding='utf-8').read()  
start = content.find('def grab_rect(self, left: int, top: int, width: int, height: int)')  
end = content.find('\n        # Use BitBlt', start)  
print('End:', end)  
print('Context:', repr(content[start:end+1])) 
